name = "hl-worker"
main = "src/index.ts"
compatibility_date = "2025-09-16"

[[d1_databases]]
binding = "DB"
database_name = "hl_leaderboard"
# 部署后使用 `wrangler d1 list` 查到真实 ID 并替换
database_id = "e858d846-53d1-46fa-9507-1840e4e7d8cb"

[[kv_namespaces]]
binding = "CACHE"
# 创建后填入 KV 命名空间 ID
id = "728c6d1b94e64ec694f51d08c5361ff6"

[vars]
# 将其设置为你的前端域名（如 Cloudflare Pages 自定义域）
ALLOWED_ORIGIN = "https://liqunhuarongdao.biboran.top"


